### ISSUE TITLE
glpi.search method loads only first 20 rows

### ISSUE THREAD

**Issue by godjan-st** [unistra/python-glpi-api#12]
GLPI API search method loads only first 20 rows, if you not specify more in range parameter. But range param is not implemented, sadly does the search method unusable for now.
Anyway repo is very helpful, thank you! Maybe I'll try to implement it by myself.

**Comment by fmenabe** [comment]
Sorry for the late reply! 

Range parameter is implemented:

```
In [1]: import glpi_api

In [2]: glpi = glpi_api.GLPI('https://**********/apirest.php/', '******', '******')

In [3]: len(glpi.search('Computer'))
Out[3]: 15

In [4]: len(glpi.search('Computer', range='0-99'))
Out[4]: 100
```

You can also find an example in the Ansible collection [here](https://github.com/unistra/ansible-collection-glpi/blob/8f154447df968cf2dc5a8f2f87fb868bb6fad92d/plugins/inventory/inv.py#L207).
