### ISSUE TITLE
Invalid path separator while being run under Windows

### ISSUE THREAD

**Issue by dakrup** [unistra/python-glpi-api#2]
The method _set_method(self, *endpoints) generates an invalid path due to os.path routine under Windows (invalid path separator):
`
    def _set_method(self, *endpoints):
        """Generate the URL from ``endpoints``."""
        return os.path.join(self.url, *[str(endpoint) for endpoint in endpoints])
`
We can get the path as: https://127.0.0.1/glpi/apirest.php\search/Computer ... then GLPI reports a 404 error.
It's safer to construct path directly from *endpoints together with UNIX path separator.

**Comment by fmenabe** [comment]
Thanks for pointing the bug. I can't test on Windows, can you confirm it works well now?

**Comment by dakrup** [comment]
> Thanks for pointing the bug. I can't test on Windows, can you confirm it works well now?

Yes, now it works just fine. Thank you!
