### ISSUE TITLE
Wrong version for v0.3.1

### ISSUE THREAD

**Issue by mxjeff** [unistra/python-glpi-api#6]
[`setup.py`](https://github.com/unistra/python-glpi-api/blob/0.3.1/setup.py) still mentions 0.3.0 in 0.3.1 release.

Then (on Debian GNU/Linux 11 (bullseye)):
```sh
python3 -m venv glpi
./glpi/bin/pip install git+https://github.com/unistra/python-glpi-api.git@0.3.1
./glpi/bin/pip list | grep glpi-api
glpi-api      0.3.0
```
Same with [the tar ball](https://github.com/unistra/python-glpi-api/archive/refs/tags/0.3.1.tar.gz): `pip install https://github.com/unistra/python-glpi-api/archive/refs/tags/0.3.1.tar.gz`

**Comment by fmenabe** [comment]
Corrected, thanks for the catch!
